
--esta wea no se si es necesaria crearla porke tenia la idea de hacer esto en la tabla empleados
CREATE TABLE BC_BR_BV_RM_SESION(
    ID_SESION NUMBER,
    NOMBRE_SESION VARCHAR2(10),
    CONSTRAINT PK_BC_BR_BV_RM_SESION PRIMARY KEY (ID_SESION)
);

CREATE TABLE BC_BR_BV_RM_SUCURSAL (
    ID_SUCURSAL NUMBER,
    NOMBRE_SUCURSAL VARCHAR2(30),
    DIRECCION VARCHAR2(200),
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID_SUCURSAL)
);
--tienen k crear algun dato de estos igual q despues son mostrados en las opciones cuando se 
--entra a la wea de crear un empleado (nuevo empleado)
CREATE TABLE BC_BR_BV_RM_TIPO_CUENTA (
    ID_TIPO_CUENTA NUMBER,
    TIPO_CUENTA VARCHAR2(20),
    CONSTRAINT PK_TIPO_CUENTA PRIMARY KEY (ID_TIPO_CUENTA)
);
--estos tambn
CREATE TABLE BC_BR_BV_RM_BANCO_EMPLEADO (
    ID_BANCO_EMPLEADO NUMBER,
    NOMBRE_BANCO VARCHAR2(15),
    CONSTRAINT PK_BANCO_EMPLEADO PRIMARY KEY (ID_BANCO_EMPLEADO)
);

--estas weas yo caxo q hay q cambiarlos
CREATE TABLE BC_BR_BV_RM_HORA_INGRESO (
    ID_HORA_INGRESO NUMBER,
    HORA_INGRESO NUMBER,
    CONSTRAINT PK_HORA_INGRESO PRIMARY KEY (ID_HORA_INGRESO)
);
--tambn
CREATE TABLE BC_BR_BV_RM_HORA_SALIDA (
    ID_HORA_SALIDA NUMBER,
    HORA_SALIDA NUMBER,
    CONSTRAINT PK_HORA_SALIDA PRIMARY KEY (ID_HORA_SALIDA)
);

CREATE TABLE BC_BR_BV_RM_TURNOS (
    ID_TURNO NUMBER,
    ID_HORA_INGRESO NUMBER,
    ID_HORA_SALIDA NUMBER,
    CONSTRAINT PK_TURNOS PRIMARY KEY (ID_TURNO),
    CONSTRAINT FK_TURNO_HORA_INGRESO FOREIGN KEY (ID_HORA_INGRESO) REFERENCES BC_BR_BV_RM_HORA_INGRESO(ID_HORA_INGRESO),
    CONSTRAINT FK_TURNO_HORA_SALIDA FOREIGN KEY (ID_HORA_SALIDA) REFERENCES BC_BR_BV_RM_HORA_SALIDA(ID_HORA_SALIDA)
);

CREATE TABLE BC_BR_BV_RM_EMPLEADOS (
    ID_EMPLEADO NUMBER,
    NOMBRE_EMPLEADO VARCHAR2(20),
    APELLIDO1_EMPLEADO VARCHAR2(50),
    APELLIDO2_EMPLEADO VARCHAR2(50),
    FECHA_CONTRATACION DATE,
    NUMERO_TELEFONO NUMBER,
    ID_AREA_TRABAJO NUMBER,
    ID_SUCURSAL NUMBER,
    ID_TURNO NUMBER,
    HORAS_EXTRAS NUMBER,
    ID_SESION NUMBER,
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FK_EMPLEADO_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES BC_BR_BV_RM_SUCURSAL(ID_SUCURSAL),
    CONSTRAINT FK_EMPLEADO_TURNO FOREIGN KEY (ID_TURNO) REFERENCES BC_BR_BV_RM_TURNOS(ID_TURNO),
    CONSTRAINT FK_ID_SESION FOREIGN KEY (ID_SESION) REFERENCES BC_BR_BV_RM_SESION(ID_SESION)
);

CREATE TABLE BC_BR_BV_RM_AREA_TRABAJO (
    ID_AREA_TRABAJO NUMBER,
    NOMBRE_AREA_TRABAJO VARCHAR2(20),
    ID_JEFE_AREA_TRABAJO NUMBER,
    SUELDO NUMBER,
    VALOR_HORA_EXTRA NUMBER,
    CONSTRAINT PK_AREA_TRABAJO PRIMARY KEY (ID_AREA_TRABAJO, ID_JEFE_AREA_TRABAJO),
    CONSTRAINT FK_JEFE_AREA_TRABAJO FOREIGN KEY (ID_JEFE_AREA_TRABAJO) REFERENCES BC_BR_BV_RM_EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE BC_BR_BV_RM_DATOS_PAGOS (
    ID_EMPLEADO NUMBER,
    NRO_CUENTA NUMBER,
    ID_TIPO_CUENTA NUMBER,
    ID_BANCO_EMPLEADO NUMBER,
    CONSTRAINT PK_DATOS_PAGOS PRIMARY KEY (ID_EMPLEADO, NRO_CUENTA, ID_TIPO_CUENTA, ID_BANCO_EMPLEADO),
    CONSTRAINT FK_DATOS_PAGOS_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES BC_BR_BV_RM_EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_DATOS_PAGOS_TIPO_CUENTA FOREIGN KEY (ID_TIPO_CUENTA) REFERENCES BC_BR_BV_RM_TIPO_CUENTA(ID_TIPO_CUENTA),
    CONSTRAINT FK_DATOS_PAGOS_BANCO_EMPLEADO FOREIGN KEY (ID_BANCO_EMPLEADO) REFERENCES BC_BR_BV_RM_BANCO_EMPLEADO(ID_BANCO_EMPLEADO)
);

--procedimiento almacenado para insertar datos en la tabla empleados
CREATE OR REPLACE PROCEDURE insertar_empleado (
    p_nombre_empleado       IN BC_BR_BV_RM_EMPLEADOS.NOMBRE_EMPLEADO%TYPE,
    p_apellido1_empleado    IN BC_BR_BV_RM_EMPLEADOS.APELLIDO1_EMPLEADO%TYPE,
    p_apellido2_empleado    IN BC_BR_BV_RM_EMPLEADOS.APELLIDO2_EMPLEADO%TYPE,
    p_fecha_contratacion    IN BC_BR_BV_RM_EMPLEADOS.FECHA_CONTRATACION%TYPE,
    p_numero_telefono       IN BC_BR_BV_RM_EMPLEADOS.NUMERO_TELEFONO%TYPE,
    p_id_area_trabajo       IN BC_BR_BV_RM_EMPLEADOS.ID_AREA_TRABAJO%TYPE,
    p_id_sucursal           IN BC_BR_BV_RM_EMPLEADOS.ID_SUCURSAL%TYPE,
    p_id_turno              IN BC_BR_BV_RM_EMPLEADOS.ID_TURNO%TYPE DEFAULT NULL,
    p_horas_extras          IN BC_BR_BV_RM_EMPLEADOS.HORAS_EXTRAS%TYPE DEFAULT 0,
    p_id_sesion             IN BC_BR_BV_RM_EMPLEADOS.ID_SESION%TYPE DEFAULT NULL
) AS
BEGIN
    INSERT INTO BC_BR_BV_RM_EMPLEADOS (
        NOMBRE_EMPLEADO, APELLIDO1_EMPLEADO, APELLIDO2_EMPLEADO,
        FECHA_CONTRATACION, NUMERO_TELEFONO, ID_AREA_TRABAJO,
        ID_SUCURSAL, ID_TURNO, HORAS_EXTRAS, ID_SESION
    ) VALUES (
        p_nombre_empleado, p_apellido1_empleado, p_apellido2_empleado,
        p_fecha_contratacion, p_numero_telefono, p_id_area_trabajo,
        p_id_sucursal, p_id_turno, p_horas_extras, p_id_sesion
    );
    COMMIT;
END insertar_empleado;
/


--trigger para crear las claves primarias (id_empleado) de la tabla empleados
CREATE OR REPLACE TRIGGER BC_BR_BV_RM_PRIMKEY_EMPLEADOS
BEFORE INSERT
ON BC_BR_BV_RM_EMPLEADOS
FOR EACH ROW 
BEGIN
	SELECT MAX(ID_EMPLEADO)+1 INTO :NEW.ID_EMPLEADO
	FROM BC_BR_BV_RM_EMPLEADOS;
	IF(:NEW.ID_EMPLEADO IS NULL)THEN
		:NEW.ID_EMPLEADO := 1;
	END IF;
END;

--datos de prueba para la tabla empleados
INSERT INTO BC_BR_BV_RM_EMPLEADOS 
(ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO1_EMPLEADO, APELLIDO2_EMPLEADO, FECHA_CONTRATACION, NUMERO_TELEFONO, ID_AREA_TRABAJO, ID_SUCURSAL, ID_TURNO, HORAS_EXTRAS, ID_SESION)
VALUES ('benjamin', 'Caceres', 'Vargas', TO_DATE('2023-01-01', 'YYYY-MM-DD'), 56912345678, NULL, 1, NULL, 0, NULL);

INSERT INTO BC_BR_BV_RM_EMPLEADOS 
(ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO1_EMPLEADO, APELLIDO2_EMPLEADO, FECHA_CONTRATACION, NUMERO_TELEFONO, ID_AREA_TRABAJO, ID_SUCURSAL, ID_TURNO, HORAS_EXTRAS, ID_SESION)
VALUES ('Valeria', 'Valenzuela', 'Bravo', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 56998765432, NULL, 2, NULL, 0, NULL);

INSERT INTO BC_BR_BV_RM_EMPLEADOS 
(ID_EMPLEADO, NOMBRE_EMPLEADO, APELLIDO1_EMPLEADO, APELLIDO2_EMPLEADO, FECHA_CONTRATACION, NUMERO_TELEFONO, ID_AREA_TRABAJO, ID_SUCURSAL, ID_TURNO, HORAS_EXTRAS, ID_SESION)
VALUES ('Jose', 'Martinez', 'Diaz', TO_DATE('2023-02-01', 'YYYY-MM-DD'), 56987654321, NULL, 3, NULL, 0, NULL);


--datos de prueba para las areas de trabajo
INSERT INTO BC_BR_BV_RM_AREA_TRABAJO (ID_AREA_TRABAJO, NOMBRE_AREA_TRABAJO, ID_JEFE_AREA_TRABAJO, SUELDO, VALOR_HORA_EXTRA) 
VALUES (1, 'Recursos Humanos', 1, 800000, 5000);

INSERT INTO BC_BR_BV_RM_AREA_TRABAJO (ID_AREA_TRABAJO, NOMBRE_AREA_TRABAJO, ID_JEFE_AREA_TRABAJO, SUELDO, VALOR_HORA_EXTRA) 
VALUES (2, 'Finanzas', 2, 1200000, 7000);

INSERT INTO BC_BR_BV_RM_AREA_TRABAJO (ID_AREA_TRABAJO, NOMBRE_AREA_TRABAJO, ID_JEFE_AREA_TRABAJO, SUELDO, VALOR_HORA_EXTRA) 
VALUES (3, 'Operaciones', 1, 1000000, 6000);


