CREATE OR REPLACE PROCEDURE BC_BR_BV_RM_INSERTAR_BANCO_EMPLEADO (
    P_ID_BANCO_EMPLEADO    IN NUMBER,
    P_NOMBRE_BANCO         IN VARCHAR2
)
AS
BEGIN
    LOCK TABLE BC_BR_BV_RM_BANCO_EMPLEADO IN ROW EXCLUSIVE MODE;
    
    -- Insertar datos del banco empleado
    INSERT INTO BC_BR_BV_RM_BANCO_EMPLEADO (
        ID_BANCO_EMPLEADO, NOMBRE_BANCO
    ) VALUES (
        P_ID_BANCO_EMPLEADO, P_NOMBRE_BANCO
    );
    
    COMMIT;
EXCEPTION
    WHEN STORAGE_ERROR THEN
        RAISE_APPLICATION_ERROR(-6500, 'HAY PROBLEMAS DE MEMORIA');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20010, 'UPSI FALLÉ =)');
    ROLLBACK;
END;