create or replace TRIGGER BC_BR_BV_RM_PRIMKEY_EMPLEADOS
BEFORE INSERT
ON BC_BR_BV_RM_EMPLEADOS
FOR EACH ROW
BEGIN
    SELECT MAX(ID_EMPLEADO)+1 INTO :NEW.ID_EMPLEADO
    FROM BC_BR_BV_RM_EMPLEADOS;
    IF(:NEW.ID_EMPLEADO IS NULL)THEN
        :NEW.ID_EMPLEADO := 1;
    END IF;
END;