CREATE TABLE BC_BR_BV_RM_SESION(
    ID_SESION NUMBER,
    NOMBRE_SESION VARCHAR2(10),
    CONSTRAINT PK_BC_BR_BV_RM_SESION PRIMARY KEY (ID_SESION)
);

CREATE TABLE BC_BR_BV_RM_SUCURSAL (
    ID_SUCURSAL NUMBER,
    NOMBRE_SUCURSAL VARCHAR2(30),
    DIRECCION VARCHAR2(200),
    CONSTRAINT PK_SUCURSAL PRIMARY KEY (ID_SUCURSAL)
);

CREATE TABLE BC_BR_BV_RM_TIPO_CUENTA (
    ID_TIPO_CUENTA NUMBER,
    TIPO_CUENTA VARCHAR2(20),
    CONSTRAINT PK_TIPO_CUENTA PRIMARY KEY (ID_TIPO_CUENTA)
);

CREATE TABLE BC_BR_BV_RM_BANCO_EMPLEADO (
    ID_BANCO_EMPLEADO NUMBER,
    NOMBRE_BANCO VARCHAR2(15),
    CONSTRAINT PK_BANCO_EMPLEADO PRIMARY KEY (ID_BANCO_EMPLEADO)
);


CREATE TABLE BC_BR_BV_RM_TURNOS (
    ID_TURNO NUMBER,
    ID_EMPLEADO NUMBER,
    FECHA DATE,
    HORA_ENTRADA DATE,
    HORA_sALIDA DATE
    CONSTRAINT PK_TURNOS PRIMARY KEY (ID_TURNO),
    CONSTRAINT FK_EMPLEADOS_TURNO FOREIGN KEY (ID_EMPLEADO) REFERENCES  BC_BR_BV_RM_EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE BC_BR_BV_RM_EMPLEADOS (
    ID_EMPLEADO NUMBER,
    NOMBRE_EMPLEADO VARCHAR2(20),
    APELLIDO1_EMPLEADO VARCHAR2(50),
    APELLIDO2_EMPLEADO VARCHAR2(50),
    FECHA_CONTRATACION DATE,
    NUMERO_TELEFONO NUMBER,
    ID_AREA_TRABAJO NUMBER,
    ID_SUCURSAL NUMBER,
    ID_TURNO NUMBER,
    HORAS_EXTRAS NUMBER,
    ID_SESION NUMBER,
    USERNAME VARCHAR2(50),
    PASSWORD VARCHAR2R2(255),
    PRIMER_VEZ_INICIO_SESION NUMBER,
    SUELDO NUMBER
    CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FK_EMPLEADO_SUCURSAL FOREIGN KEY (ID_SUCURSAL) REFERENCES BC_BR_BV_RM_SUCURSAL(ID_SUCURSAL),
    CONSTRAINT FK_EMPLEADO_TURNO FOREIGN KEY (ID_TURNO) REFERENCES BC_BR_BV_RM_TURNOS(ID_TURNO),
    CONSTRAINT FK_ID_SESION FOREIGN KEY (ID_SESION) REFERENCES BC_BR_BV_RM_SESION(ID_SESION)
);

CREATE TABLE BC_BR_BV_RM_AREA_TRABAJO (
    ID_AREA_TRABAJO NUMBER,
    NOMBRE_AREA_TRABAJO VARCHAR2(20),
    ID_JEFE_AREA_TRABAJO NUMBER,
    SUELDO NUMBER,
    VALOR_HORA_EXTRA NUMBER,
    CONSTRAINT PK_AREA_TRABAJO PRIMARY KEY (ID_AREA_TRABAJO, ID_JEFE_AREA_TRABAJO),
    CONSTRAINT FK_JEFE_AREA_TRABAJO FOREIGN KEY (ID_JEFE_AREA_TRABAJO) REFERENCES BC_BR_BV_RM_EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE BC_BR_BV_RM_DATOS_PAGOS (
    ID_EMPLEADO NUMBER,
    NRO_CUENTA NUMBER,
    ID_TIPO_CUENTA NUMBER,
    ID_BANCO_EMPLEADO NUMBER,
    CONSTRAINT PK_DATOS_PAGOS PRIMARY KEY (ID_EMPLEADO, NRO_CUENTA, ID_TIPO_CUENTA, ID_BANCO_EMPLEADO),
    CONSTRAINT FK_DATOS_PAGOS_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES BC_BR_BV_RM_EMPLEADOS(ID_EMPLEADO),
    CONSTRAINT FK_DATOS_PAGOS_TIPO_CUENTA FOREIGN KEY (ID_TIPO_CUENTA) REFERENCES BC_BR_BV_RM_TIPO_CUENTA(ID_TIPO_CUENTA),
    CONSTRAINT FK_DATOS_PAGOS_BANCO_EMPLEADO FOREIGN KEY (ID_BANCO_EMPLEADO) REFERENCES BC_BR_BV_RM_BANCO_EMPLEADO(ID_BANCO_EMPLEADO)
);