CREATE OR REPLACE PROCEDURE BC_BR_BV_RM_INSERTAR_SUCURSAL (
    P_ID_SUCURSAL          IN NUMBER,
    P_NOMBRE_SUCURSAL      IN VARCHAR2,
    P_DIRECCION            IN VARCHAR2
)
AS
BEGIN
    LOCK TABLE BC_BR_BV_RM_SUCURSAL IN ROW EXCLUSIVE MODE;
    
    -- Insertar datos de la sucursal
    INSERT INTO BC_BR_BV_RM_SUCURSAL (
        ID_SUCURSAL, NOMBRE_SUCURSAL, DIRECCION
    ) VALUES (
        P_ID_SUCURSAL, P_NOMBRE_SUCURSAL, P_DIRECCION
    );
    
    COMMIT;
EXCEPTION
    WHEN STORAGE_ERROR THEN
        RAISE_APPLICATION_ERROR(-6500, 'HAY PROBLEMAS DE MEMORIA');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20010, 'UPSI FALLÉ =)');
    ROLLBACK;
END;