create or replace PROCEDURE BC_BR_BV_RM_INSERTAR_EMPLEADO (
    P_NOMBRE_EMPLEADO        IN VARCHAR2,
    P_APELLIDO1_EMPLEADO     IN VARCHAR2,
    P_APELLIDO2_EMPLEADO     IN VARCHAR2,
    P_FECHA_CONTRATACION     IN DATE,
    P_NUMERO_TELEFONO        IN NUMBER,
    P_ID_AREA_TRABAJO        IN NUMBER,
    P_ID_SUCURSAL            IN NUMBER,
    P_HORAS_EXTRAS           IN NUMBER,
    P_ID_SESION              IN NUMBER,
    P_NRO_CUENTA             IN NUMBER,
    P_ID_TIPO_CUENTA         IN NUMBER,
    P_ID_BANCO_EMPLEADO      IN NUMBER,
    P_SUELDO                 IN NUMBER
)
AS
BEGIN
    LOCK TABLE BC_BR_BV_RM_EMPLEADOS IN ROW EXCLUSIVE MODE;
    -- Insertar datos del empleado
    INSERT INTO BC_BR_BV_RM_EMPLEADOS (
        NOMBRE_EMPLEADO, APELLIDO1_EMPLEADO, APELLIDO2_EMPLEADO,
        FECHA_CONTRATACION, NUMERO_TELEFONO, ID_AREA_TRABAJO,
        ID_SUCURSAL, HORAS_EXTRAS, ID_SESION, SUELDO
    ) VALUES (
        P_NOMBRE_EMPLEADO, P_APELLIDO1_EMPLEADO, P_APELLIDO2_EMPLEADO,
        P_FECHA_CONTRATACION, P_NUMERO_TELEFONO, P_ID_AREA_TRABAJO,
        P_ID_SUCURSAL, P_HORAS_EXTRAS, P_ID_SESION, P_SUELDO
    );

    -- Insertar datos bancarios
    INSERT INTO BC_BR_BV_RM_DATOS_PAGOS (
        ID_EMPLEADO, NRO_CUENTA, ID_TIPO_CUENTA, ID_BANCO_EMPLEADO
    ) VALUES (
        (SELECT MAX(ID_EMPLEADO) FROM BC_BR_BV_RM_EMPLEADOS), -- Asumiendo que ID_EMPLEADO es autogenerado
        P_NRO_CUENTA, P_ID_TIPO_CUENTA, P_ID_BANCO_EMPLEADO
    );
        COMMIT;
    EXCEPTION
        WHEN STORAGE_ERROR THEN
            RAISE_APPLICATION_ERROR(-6500,'HAY PROBLEMAS DE MEMORIA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010,'UPSI FALLÉ =)');
    ROLLBACK;
END;